export const devicesConfig = [
  {
    name: 'Kotel1',
    deviceID: 1,
    port: 'COM3',
    baudRate: 57600,
    timeout: 2000,
    retryInterval: 1000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataKotel1',
    serviceModule: './services/kotel1Service.js',
  },
  {
    name: 'Kotel2',
    deviceID: 2,
    port: 'COM3',
    baudRate: 57600,
    timeout: 2000,
    retryInterval: 1000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataKotel2',
    serviceModule: './services/kotel2Service.js',
  },
  {
    name: 'Kotel3',
    deviceID: 3,
    port: 'COM3',
    baudRate: 9600,
    timeout: 2000,
    retryInterval: 1000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataKotel3',
    serviceModule: './services/kotel3Service.js',
  },

  {
    name: 'Hvo1',
    deviceID: 1,
    port: 'COM4',
    baudRate: 57600,
    timeout: 2000,
    retryInterval: 1000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataHvo1',
    serviceModule: './services/hvo1Service.js',
  },
  {
    name: 'Hvo2',
    deviceID: 2,
    port: 'COM4',
    baudRate: 57600,
    timeout: 2000,
    retryInterval: 1000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataHvo2',
    serviceModule: './services/hvo2Service.js',
  },
]