export const devicesConfig = [
  // {
  //   name: 'Kotel1',
  //   deviceID: 1,
  //   port: 'COM3',
  //   baudRate: 57600,
  //   timeout: 12000,
  //   retryInterval: 15000,
  //   maxRetries: 3,
  //   unstable: false,
  //   readDataFunction: 'readDataVr1',
  //   serviceModule: './services/pechVr1ModbusService.js',
  // },
  {
    name: 'Kotel2',
    deviceID: 2,
    port: 'COM3',
    baudRate: 57600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataKotel2',
    serviceModule: './services/kotel2Service.js',
  },
  // {
  //   name: 'Kotel3',
  //   deviceID: 3,
  //   port: 'COM3',
  //   baudRate: 57600,
  //   timeout: 12000,
  //   retryInterval: 15000,
  //   maxRetries: 3,
  //   unstable: false,
  //   readDataFunction: 'readDataVr2',
  //   serviceModule: './services/pechVr2ModbusService.js',
  // },
]